version: "3"

networks:
    internal:
       external: false

services:
    traefik:
        image: traefik:2.2
        ports:
            - 80:80
            - 443:443
        container_name: traefik

        volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - ./traefik.yml:/traefik.yml
                - ./traefik_conf/:/traefik_conf/
                - ./traefik_logs.log:/traefik_logs.log
        networks:
                - default
        restart: unless-stopped

    deluge:
        image: linuxserver/deluge:latest
        container_name: deluge
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TIME_Z}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.deluge.rule=Host(`deluge.razor.si`)"
            - "traefik.http.routers.deluge.entrypoints=websecure"
            - "traefik.http.routers.deluge.tls=true"
            - "traefik.http.routers.deluge.tls.certresolver=myresolver"

        volumes:
            - ${DELUGE_CONF}:/config
            - ${DELUGE_DATA}:/downloads
        networks:
            - internal
            - default
        restart: unless-stopped
 
    jellyfin:
        image: linuxserver/jellyfin
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TIME_Z}
            - UMASK_SET=022 #optional
        volumes:
            - ${JELLY_CONF}:/config
            - ${JELLY_DATA}:/data/torrents
            - /opt/vc/lib:/opt/vc/lib #optional
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.rule=Host(`jelly.razor.si`)"
            - "traefik.http.routers.jellyfin.entrypoints=websecure"
            - "traefik.http.routers.jellyfin.tls=true"
            - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"

        devices:
            - /dev/dri:/dev/dri #optional
            - /dev/vcsm:/dev/vcsm #optional
            - /dev/vchiq:/dev/vchiq #optional
            - /dev/video10:/dev/video10 #optional
            - /dev/video11:/dev/video11 #optional
            - /dev/video12:/dev/video12 #optional
        networks:
            - internal
            - default
        restart: unless-stopped


