entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

providers:
  file:
    directory: /traefik_conf

  docker: {}

certificatesResolvers:
  myresolver:
    acme:
      email: "andrej.zubin@email.com"
      storage: "acme.json"
      tlsChallenge: {}

log:
  level: debug

